KinoWebApp/KinoWebApp/Controllers/FilmController.cs
using KinoWebApp.Models;
using KinoWebApp.Persistence;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace KinoWebApp.Controllers
{
    public class FilmController : Controller
    {
        private KinoWebAppDbContext _context = new KinoWebAppDbContext();

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Film newFilm)
        {
            if (!ModelState.IsValid)
            {
                return View(newFilm);
            }

            _context.Filmy.Add(newFilm);
            _context.SaveChanges();
            return RedirectToAction("Create");
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = _context.Filmy.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Film film = _context.Filmy.Find(id);
            _context.Filmy.Remove(film);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Film film = _context.Filmy.Find(id);
            if (film == null)
            {
                return HttpNotFound();
            }
            return View(film);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Film film)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(film).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(film);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
        }
    }
}

KinoWebApp/KinoWebApp/Controllers/GatunekController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KinoWebApp.Models;
using KinoWebApp.Persistence;

namespace KinoWebApp.Controllers
{
    public class GatunekController : Controller
    {
        private KinoWebAppDbContext _context = new KinoWebAppDbContext();

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Gatunek newGatunek)
        {
            if (!ModelState.IsValid)
            {
                return View(newGatunek);
            }

            _context.Gatunki.Add(newGatunek);
            _context.SaveChanges();
            return RedirectToAction("Create");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gatunek gatunek = _context.Gatunki.Find(id);
            if (gatunek == null)
            {
                return HttpNotFound();
            }
            return View(gatunek);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Gatunek gatunek)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(gatunek).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(gatunek);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gatunek gatunek = _context.Gatunki.Find(id);
            if (gatunek == null)
            {
                return HttpNotFound();
            }
            return View(gatunek);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gatunek gatunek = _context.Gatunki.Find(id);
            _context.Gatunki.Remove(gatunek);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
        }
    }
}

KinoWebApp/KinoWebApp/Controllers/HomeController.cs
using KinoWebApp.Models;
using KinoWebApp.Persistence;
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using System.Net;

namespace KinoWebApp.Controllers
{
    public class HomeController : Controller
    {
        private KinoWebAppDbContext _context = new KinoWebAppDbContext();

        // GET: Home
        public ActionResult Index()
        {

            var film = _context.Filmy.ToList();

            //    var film = _context.Filmy.Include(i => i.ID_GAT).ToList();
            
            return View(film);
        }

        public ActionResult Kino()
        {
            return View();
        }

        public ActionResult Kontakt()
        {
            return View();
        }

        public ActionResult Gat()
        {
            var gat = _context.Gatunki.ToList();
            return View(gat);
        }

        public ActionResult Kat()
        {
            var kat = _context.Kategorie.ToList();
            return View(kat);
        }

        public ActionResult Repertuar()
        {
            var seans = _context.Seanse.ToList();
            return View(seans);
        }

        public ActionResult Cennik()
        {
            var miejsce = _context.Miejsca.ToList();
            return View(miejsce);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
        }
    }
}

KinoWebApp/KinoWebApp/Controllers/KategoriaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KinoWebApp.Models;
using KinoWebApp.Persistence;

namespace KinoWebApp.Controllers
{
    public class KategoriaController : Controller
    {
        private KinoWebAppDbContext _context = new KinoWebAppDbContext();

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Kategoria newKategoria)
        {
            if (!ModelState.IsValid)
            {
                return View(newKategoria);
            }

            _context.Kategorie.Add(newKategoria);
            _context.SaveChanges();
            return RedirectToAction("Create");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategoria kategoria = _context.Kategorie.Find(id);
            if (kategoria == null)
            {
                return HttpNotFound();
            }
            return View(kategoria);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Kategoria kategoria)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(kategoria).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(kategoria);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kategoria kategoria = _context.Kategorie.Find(id);
            if (kategoria == null)
            {
                return HttpNotFound();
            }
            return View(kategoria);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kategoria kategoria = _context.Kategorie.Find(id);
            _context.Kategorie.Remove(kategoria);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
        }
    }
}

KinoWebApp/KinoWebApp/Controllers/SeansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KinoWebApp.Models;
using KinoWebApp.Persistence;

namespace KinoWebApp.Controllers
{
    public class SeansController : Controller
    {
        private KinoWebAppDbContext _context = new KinoWebAppDbContext();

        public ActionResult Create()
        {
            ViewBag.IDF = new SelectList(_context.Filmy, "IDF", "TYTUL");
            ViewBag.NR_SALI = new SelectList(_context.Sale, "NR_SALI", "NR_SALI");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Seans seans)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.IDF = new SelectList(_context.Filmy, "IDF", "TYTUL", seans.IDF);
                ViewBag.NR_SALI = new SelectList(_context.Sale, "NR_SALI", "NR_SALI", seans.NR_SALI);
                return View(seans);
            }

            _context.Seanse.Add(seans);
            _context.SaveChanges();
            return RedirectToAction("Create");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seans seans = _context.Seanse.Find(id);
            if (seans == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDF = new SelectList(_context.Filmy, "IDF", "TYTUL", seans.IDF);
            ViewBag.NR_SALI = new SelectList(_context.Sale, "NR_SALI", "NR_SALI", seans.NR_SALI);
            return View(seans);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Seans seans)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(seans).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            ViewBag.IDF = new SelectList(_context.Filmy, "IDF", "TYTUL", seans.IDF);
            ViewBag.NR_SALI = new SelectList(_context.Sale, "NR_SALI", "NR_SALI", seans.NR_SALI);
            return View(seans);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Seans seans = _context.Seanse.Find(id);
            if (seans == null)
            {
                return HttpNotFound();
            }
            return View(seans);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Seans seans = _context.Seanse.Find(id);
            _context.Seanse.Remove(seans);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
        }
    }
}

KinoWebApp/KinoWebApp/Views/Home/Cennik.cshtml
@model IList<KinoWebApp.Models.Miejsce>

@{
    ViewBag.Title = "Cennik";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="title">Cennik</div>
    <table>
        <thead>
            <tr>
                <th>NR_SALI</th>
                <th>NR_MIEJSCA</th>
                <th>CENA</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var i in Model)
            {
                <tr>
                    <td>@i.NR_SALI</td>
                    <td>@i.NR_MIEJSCA</td>
                    <td>@i.CENA</td>
                </tr>
            }
        </tbody>
    </table>

KinoWebApp/KinoWebApp/Views/Home/Gat.cshtml
@model IList<KinoWebApp.Models.Gatunek>

@{
    ViewBag.Title = "Gat";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="title">Kategorie</div>
<table>
    <thead>
        <tr>
            <th>ID_GAT</th>
            <th>NAZWA</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var i in Model)
        {
            <tr>
                <td>@i.ID_GAT</td>
                <td>@i.NAZWA</td>
                <td>@Html.ActionLink("Usun", "Delete", "Gatunek", new { id = i.ID_GAT }, i.ID_GAT) | @Html.ActionLink("Edytuj", "Edit", "Gatunek", new { id = i.ID_GAT }, i.ID_GAT)</td>
            </tr>
        }
    </tbody>
</table>

KinoWebApp/KinoWebApp/Views/Home/Index.cshtml
@model IList<KinoWebApp.Models.Film>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Kino - Filmy";
}

<div class="title">Filmy</div>
    <table>
        <thead>
            <tr>
                <th>TYTUL</th>
                <th>REZYSER</th>
                <th>DLUGOSC</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var i in Model)
            {
                <tr>
                    <td>@i.TYTUL</td>
                    <td>@i.REZYSER</td>
                    <td>@i.DLUGOSC</td>
                    <td>@Html.ActionLink("Usun", "Delete", "Film", new { id = i.IDF }, i.IDF) | @Html.ActionLink("Edytuj", "Edit", "Film", new { id = i.IDF }, i.IDF)</td>
                </tr>
            }
        </tbody>
    </table>

KinoWebApp/KinoWebApp/Views/Home/Kat.cshtml
@model IList<KinoWebApp.Models.Kategoria>

@{
    ViewBag.Title = "Kat";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="title">Kategorie</div>
<table>
    <thead>
        <tr>
            <th>IDK</th>
            <th>NAZWA</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var i in Model)
            {
            <tr>
                <td>@i.IDK</td>
                <td>@i.NAZWA</td>
                <td>@Html.ActionLink("Usun", "Delete", "Kategoria", new { id = i.IDK }, i.IDK) | @Html.ActionLink("Edytuj", "Edit", "Kategoria", new { id = i.IDK }, i.IDK)</td>
            </tr>
        }
    </tbody>
</table>

KinoWebApp/KinoWebApp/Views/Home/Kino.cshtml
@{
    ViewBag.Title = "Kino";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="title">Kino</div>
<div class="info">
    Lorem ipsum...
</div>

KinoWebApp/KinoWebApp/Views/Home/Kontakt.cshtml
@{
    ViewBag.Title = "Kontakt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="title">Kontakt</div>
<div class="info">
    Ipsum lorem...
</div>

KinoWebApp/KinoWebApp/Views/Home/Repertuar.cshtml
@model IList<KinoWebApp.Models.Seans>

@{
    ViewBag.Title = "Repertuar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="title">Repertuar</div>
    <table>
        <thead>
            <tr>
                <th>IDF</th>
                <th>NR_SALI</th>
                <th>TERMIN</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var i in Model)
            {
            <tr>
                <td>@i.IDF</td>
                <td>@i.NR_SALI</td>
                <td>@i.TERMIN</td>
                <td>@Html.ActionLink("Usun", "Delete", "Seans", new { id = i.IDS }, i.IDS) | @Html.ActionLink("Edytuj", "Edit", "Seans", new { id = i.IDS }, i.IDS)</td>
            </tr>
            }
        </tbody>
    </table>